[package]
name = "football_card"
version = "1.0.0"
authors = []

[addresses]
card_addrx = "0x42"
std = "0x1"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
